name: typescipt_action
 
on:
  push:
    branches: 
      - "**"

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.16.0]
 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install    
      - name: run linter
        run: | 
          npm run lint
      - name: run test
        run: | 
          npm run test